name: API Docs

on: # TODO: determine best event hook (release, etc)
  workflow_dispatch:

env:
  DOC_LOCATION: build/dokka/htmlMultiModule
  GH_PAGES_BRANCH: api-docs
  PUBLISH_GH_PAGES: false # toggle publishing on github pages branch
  PUBLISH_ARTIFACT: true # toggle publishing all docs as artifact

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Generate API Docs
        run: |
          ./gradlew dokkaHtmlMultiModule
      - name: Stage in branch
        if: env.PUBLISH_GH_PAGES == 'true'
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.GH_PAGES_BRANCH }}
          publish_dir: ${{ env.DOC_LOCATION }}
          destination_dir: .
          allow_empty_commit: false # optional, default is false
          user_name: AWS CI
          user_email: nobody@amazonaws.com
          commit_message: Update docs
          disable_nojekyll: false
          enable_jekyll: false
      - name: Upload Complete Artifact
        if: env.PUBLISH_ARTIFACT == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: all-api-docs
          path: ${{ env.DOC_LOCATION }}
      - name: Where is everything
        run: |
          set -x
          pwd
          find .
          ls -l ${{ env.DOC_LOCATION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: api-docs
          files: |
            ${{ env.DOC_LOCATION }}/all-api-docs.zip
            ${{ env.DOC_LOCATION }}/package-list